// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'isDone': string;
  'listItem': string;
  'listItemBtn': string;
  'listItemText': string;
  'updateInput': string;
}
export const cssExports: CssExports;
export default cssExports;
